[Srv]
;服务端口
;Service port
Port=8833
;4核CPU服务器推荐 MaxConn 150 ListenQueue 50或100;
;最大并发连接
;Maximum concurrent connection
MaxConn=150
;监听队列大小
;Listen queue size
ListenQueue=100
;文件上传目录
;File upload directory
UpDir=.\uploads
UpPath=/up/
;日志设置
;Log configuration
LogDir=.\log
CacheSize=10
MaxDays=30
;脚本目录
;Script directory
Script=.\script
;静态文件目录
;Static file directory
DocRoot=.\www
;GZIP压缩
;GZIP compression
GZip=1
;JavaScript跨域
;Cross-Origin Resource Sharing (CORS)
CORS=1